const ON_REMOVE_WORD = 'ON_REMOVE_WORD';
const ON_SWITCH_STATUS = 'ON_SWITCH_STATUS';
const ON_ADD_WORD = 'ON_ADD_WORD';
const FETCH_DATA_WORDS = 'FETCH_DATA_WORDS';
const ON_SET_FILTER_MODE = 'ON_SET_FILTER_MODE';

export default {
  ON_REMOVE_WORD,
  ON_SWITCH_STATUS,
  ON_ADD_WORD,
  FETCH_DATA_WORDS,
  ON_SET_FILTER_MODE,
};
